project:
  type: website

website:
  title: "Lucas documentation."
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Java"
        menu:
          - text: "Stream"
            href: ./java-concepts/java-concepts-stream.qmd
          - text: "Optional"
            href: ./java-concepts/java-concepts-optional.qmd
          - text: "Testing"
            href: ./java-concepts/java-concepts-test.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: superhero
    toc: true
    toc-depth: 2
    code-fold: true

editor:
  default-view: source
