project:
  type: website
website:
  title: Lucas documentation.
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Java
        menu:
          - text: Stream
            href: ./java-concepts/java-concepts-stream.qmd
          - text: Optional
            href: ./java-concepts/java-concepts-optional.qmd
          - text: Testing
            href: ./java-concepts/java-concepts-test.qmd
      - text: Programming
        menu:
          - text: Dependency Injection
            href: ./programming-concepts/dependecy-injection.qmd
      - text: Spring-Boot
        menu:
          - text: Service Layer
            href: ./spring-boot/service-layer.qmd
          - text: Controller Layer
            href: ./spring-boot/controller-layer.qmd
format:
  html:
    theme: superhero
    toc: true
    toc-depth: 2
    code-fold: true
editor:
  default-view: source
