name: Publish Quarto Site

on:
  push:
    branches:
      - main
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      - name: Install R if needed
        uses: r-lib/actions/setup-r@v2
        if: "contains(join(fromJSON('[\"' + join(yaml.load(readFile('./_quarto.yml')), '\",\"') + '\"]')), 'rmd')"
        with:
          r-version: '4.x'

      - name: Install Python if needed
        uses: actions/setup-python@v4
        if: "contains(join(fromJSON('[\"' + join(yaml.load(readFile('./_quarto.yml')), '\",\"') + '\"]')), 'ipynb')"
        with:
          python-version: '3.x'
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
